spring.application.name=Trellite

spring.datasource.url=jdbc:postgresql://localhost:5432/trellite
spring.datasource.username=kshitiz
spring.datasource.password=god_Usopp500
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=Q+gb4V/yOqr+lS7T1ekTg5mJ46T2PX1beMdwVV+yuL4=
jwt.expiration=1800000