spring.application.name=Trellite

spring.datasource.url=jdbc:postgresql://localhost:5432/trellite
spring.datasource.username=kshitiz
spring.datasource.password=god_Usopp500

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
